# Generated by Django 5.0.7 on 2024-08-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_name', models.CharField(max_length=100)),
                ('categorie', models.CharField(default='', max_length=100)),
                ('subcategorie', models.CharField(default='', max_length=50)),
                ('prix', models.ImageField(default=0, upload_to='')),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(max_length=15),
        ),
    ]
