# Generated by Django 5.0.7 on 2024-08-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomeapp', '0002_produit_alter_contact_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit_name', models.CharField(max_length=100)),
                ('categorie', models.CharField(default='', max_length=100)),
                ('subcategorie', models.CharField(default='', max_length=50)),
                ('prix', models.IntegerField(default=0)),
                ('desc', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='images/images')),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
