# Generated by Django 5.0.7 on 2024-08-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomeapp', '0003_categorie_alter_produit_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oid', models.CharField(blank=True, max_length=150)),
                ('amountpaid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paiementstatus', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=90)),
                ('name', models.CharField(max_length=90)),
                ('addresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('pays', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
