# Generated by Django 5.0.7 on 2024-08-14 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomeapp', '0005_remove_orders_amountpaid_remove_orders_oid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_message',
            field=models.CharField(default='Commande reçue', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomeapp.orders'),
        ),
    ]
